import type { Metadata } from "next";
import { Molengo } from "next/font/google"
import "./globals.css";

const geist = Molengo({
  weight: "400"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geist.className} tracking-wider`}>
          
          <main>
            
            {children}
          </main>
      </body>
    </html>
  );
}
